CREATE TABLE `desks` (
  `DESK_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESK_NUMBER` varchar(20) DEFAULT NULL,
  `OFFICE_SPACE_ID` int(11) NOT NULL,
  `ASSIGNED_USER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`DESK_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
