CREATE TABLE `office_spaces` (
  `OFFICE_SPACE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `OFFICE_SPACE_NAME` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`OFFICE_SPACE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
